### PR TITLE
Events fix.

### PR DESCRIPTION
**Pull request by Haocen**
Events fix.
1. Forcible trigger 'play' event when media start playing.
2. Forcible trigger 'canplay' event before 'play' event when autoplay is set in options.

Tested on:
1. Chrome for Windows Version 54.0.2840.99 m (64-bit)
2. Firefox 49.0.2
3. Microsoft Edge 25.10586.0.0 (EdgeHTML 13.10586)

### CODE REVIEW

**Comment by DIYgod** [comment]
@Haocen In this way, `play` event will be triggered twice...

**Comment by Haocen** [comment]
@DIYgod Hi, can you let me know which browser are you testing with?

**Comment by DIYgod** [comment]
`play` event will be triggered in `play` event and `canplay` event

**Comment by Haocen** [comment]
@DIYgod I know it looked that way...
But due to the weird implementation of major browsers this fix does forcible trigger the `play` event when `autoplay` is set to true.

I myself would recommend implement some more proper life cycle deducer and proxy all basic events listed [here](http://www.w3schools.com/tags/ref_av_dom.asp).

**Comment by DIYgod** [comment]
There are another way to fix this: https://github.com/DIYgod/APlayer/issues/87#issuecomment-261143208, and this way will result in new problem.

Proxy all basic events is unnecessary, because you can bind event in `ap.audio` directly.

**Pull request closed without merging**
